# Generated by Django 3.2.25 on 2024-08-23 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasTuristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catXturNombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Turistica',
            fields=[
                ('turCodigo', models.AutoField(primary_key=True, serialize=False)),
                ('turTitulo_1', models.CharField(max_length=255)),
                ('turDescripcion_1', models.TextField(max_length=2000)),
                ('turURLImagen_1', models.CharField(max_length=1000)),
                ('turTitulo_2', models.CharField(max_length=255)),
                ('turDescripcion_2', models.TextField(max_length=2000)),
                ('turURLImagen_2', models.CharField(max_length=1000)),
                ('turTitulo_3', models.CharField(max_length=255)),
                ('turDescripcion_3', models.TextField(max_length=2000)),
                ('turURLImagen_3', models.CharField(max_length=1000)),
                ('turFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('catXturNombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turisticas.categoriasturisticas')),
            ],
        ),
    ]
