# Generated by Django 3.2.25 on 2024-08-23 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasNacionalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catXnacNombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('nacCodigo', models.AutoField(primary_key=True, serialize=False)),
                ('nacTitulo_1', models.CharField(max_length=255)),
                ('nacDescripcion_1', models.TextField(max_length=2000)),
                ('nacURLImagen_1', models.CharField(max_length=1000)),
                ('nacTitulo_2', models.CharField(max_length=255)),
                ('nacDescripcion_2', models.TextField(max_length=2000)),
                ('nacURLImagen_2', models.CharField(max_length=1000)),
                ('nacTitulo_3', models.CharField(max_length=255)),
                ('nacDescripcion_3', models.TextField(max_length=2000)),
                ('nacURLImagen_3', models.CharField(max_length=1000)),
                ('nacFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('catXnacNombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nacionalidades.categoriasnacionalidades')),
            ],
        ),
    ]
