# Generated by Django 3.2.25 on 2024-10-08 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nacionalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_visualizado', models.FloatField()),
                ('fecha_visualizacion', models.DateTimeField(auto_now_add=True)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nacionalidades.nacionalidad')),
            ],
        ),
    ]
