# Generated by Django 3.2.25 on 2024-08-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosYasuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
